version: '3'
services:
  redis:
    hostname: "redis"
    image: "redis:alpine"
    ports:
      - "6379:6379"
  zookeeper:
    hostname: "zookeeper"
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    hostname: "kafka"
    image: wurstmeister/kafka
    links:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_CREATE_TOPICS: "platform-market-price-updates:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  token-exchange:
    hostname: "token-exchange"
    build:
      context: .
      dockerfile: Dockerfile
    image: docker.io/library/token-exchange:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    links:
      - redis
      - kafka

