apiVersion: v1
kind: Pod
metadata:
  name: token-exchange-app
  labels:
    name: token-exchange-app
spec:
  containers:
    - image: wurstmeister/kafka
      name: kafka
      env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: KAFKA_MESSAGE_MAX_BYTES
          value: "2000000"
        - name: KAFKA_CREATE_TOPICS
          value: "platform-market-price-updates:1:1"
      ports:
        - containerPort: 9092
    - image: docker.io/library/token-exchange:0.0.1-SNAPSHOT
      name: token-exchange
      ports:
        - containerPort: 8080
    - image: redis:alpine
      name: redis
      ports:
        - containerPort: 6379
    - image: wurstmeister/zookeeper
      name: zookeeper
      ports:
        - containerPort: 2181
